version: '3.8'
services:
    mymongodb:
        image: mongodb/mongodb-community-server:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
        command: >
            /bin/bash -c "
            mongod &
            until mongosh --eval 'db.runCommand({ ping: 1 })' > /dev/null 2>&1; do
              echo 'Waiting for MongoDB to start...';
              sleep 1;
            done;
            tail -f /dev/null
            "
    node-app:
        build: .
        ports:
            - 4000:4000
        depends_on:
            - mymongodb
volumes:
    mongodata:
        driver: local
